BASH_COMPLETION_PATH="$HOME/.bash_completion"
BASHRC_PATH="$HOME/.bashrc"

if [ -n "$BASH_VERSION" ]; then
  [ -f $BASHRC_PATH ] && . $BASHRC_PATH
  [ -f $BASH_COMPLETION_PATH ] && . $BASH_COMPLETION_PATH
fi

export PATH="/usr/local/sbin:$PATH"
