# Warning that bash is deprecated no more
export BASH_SILENCE_DEPRECATION_WARNING=1
# Use gruvbox as standard theme for previews
export BAT_THEME=gruvbox-dark
# Integrate brew
export PATH=${HOME}/.brew/bin:${PATH}
# Integrate local bins
export PATH="$PATH:$HOME/.bin"
# Load some conf if there is some
[ -s "$HOME/.bashrc" ] && \. "$HOME/.bashrc"
# Complete bash
[ -f $(brew --prefix)/etc/bash_completion ] && \. $(brew --prefix)/etc/bash_completion

# ruby versions (TODO: move to asdf)
eval "$(rbenv init - bash)"

# node versions (TODO: move to asdf)
export NVM_DIR=~/.nvm
source $(brew --prefix nvm)/nvm.sh

# Integrate starship (replace PS1_PROMPT)
eval "$(starship init bash)"
