# Init asdf
. "$(brew --prefix asdf)/libexec/asdf.sh"
# Init asdf-completion
. "$(brew --prefix asdf)/etc/bash_completion.d/asdf.bash"

# Update asdf go env
go_path="$(asdf where golang)"
if [[ -n "${go_path}" ]]; then
  export GOPATH=$(asdf where golang)/packages
  export GOROOT=$(asdf where golang)/go
  export PATH="${PATH}:$(go env GOPATH)/bin"
fi

# Init bash-completion
[[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"

# Custom conf
alias tmux="tmux -2"
export LC_ALL=en_US.UTF-8

# Init starship
eval "$(starship init bash)"

# Init dircolors
# export LSCOLORS="Gxfxcxdxbxegedabagacad
alias ls='ls -F -G'
