BASH_COMPLETION_PATH="$HOME/.bash_completion"
BASHRC_PATH="$HOME/.bashrc"

if [ -n "$BASH_VERSION" ]; then
  [ -f $BASHRC_PATH ] && . $BASHRC_PATH
  [ -f $BASH_COMPLETION_PATH ] && . $BASH_COMPLETION_PATH
fi

export PATH="/usr/local/sbin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion" ] && . "/usr/local/opt/nvm/etc/bash_completion"  # This loads nvm bash_completion
