live_config_reload = true
import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
decorations     = "Full"
dynamic_padding = false
dynamic_title   = true
opacity         = 1.0
startup_mode    = "Windowed"
title           = "In <username> We Trust"
option_as_alt   = "Both"

[window.padding]
x = 0
y = 0

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
  { key = "J",     mods = "Alt", chars = "\u001B[B" },
  { key = "K",     mods = "Alt", chars = "\u001B[A" },
  { key = "H",     mods = "Alt", chars = "\u001B[D" },
  { key = "L",     mods = "Alt", chars = "\u001B[C" },
  { key = "L",     mods = "Control", action = "ClearLogNotice" },
  { key = "L",     mods = "Control", chars = "\f" },
]

[scrolling]
history = 12000

[font]
builtin_box_drawing = false
size                = 13.0

[font.glyph_offset]
x = 0
y = 0

[font.bold]
family = "Hack Nerd Font Mono"
style  = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style  = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style  = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style  = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = false
